{
 "title": "Geofencing",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "System in and out", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sensor location kafka source total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOut{operator_name=~\"Source:.*\"})"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSe"
    }
   ]
  },
  {
   "title": "Geofence evens kafka sink  total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOut{operator_name=\"geofence_event_sink_v1:_Writer\"})"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSe"
    }
   ]
  },
  {
   "title": "Sensor location kafka source per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{operator_name=~\"Source:.*\"})"
    }
   ]
  },
  {
   "title": "Geofence evens kafka sink per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 9 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsInPerSecond{operator_name=\"geofence_event_sink_v1:_Writer\"})"
    }
   ]
  },
  {
   "title": "Geofence evens kafka sink per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_lag_max)"
    }
   ]
  },
  { "title": "Geofence operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Sensor location kafka source per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{operator_name=~\"geofence_operator_v1\"})"
    }
   ]
  }
 ]
}